---
- name: Start minikube
  shell: minikube start --vm-driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost
  ignore_errors: yes

- name: Start nginx ingress
  shell: minikube addons enable ingress

- name: Start minikube dashboard
  shell: minikube addons enable dashboard && minikube dashboard & sleep 10s

- name: Configure upstream for dashboard
  shell: kubectl apply -f /vagrant/kubernetes/dashboard.yml
