---
- name: Start minikube
  shell: minikube start --vm-driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost
  ignore_errors: yes

- name: Start nginx ingress
  shell: minikube addons enable ingress

- name: Start minikube dashboard
  shell: minikube addons enable dashboard && minikube dashboard &

- name: Enable local registry
  shell: minikube addons enable registry

- name: Download helm installer
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
    dest: /tmp/get_helm.sh
    mode: 'a+x'

- name: Install helm
  shell: /tmp/get_helm.sh && helm init --wait

- name: Install prometheus operator
  shell: kubectl apply -f /vagrant/kubernetes/monitoring-namespace.yml && \
    helm upgrade --install monitoring stable/prometheus-operator --namespace=monitoring 

- name: Start minikube dashboard
  shell: minikube addons enable dashboard && minikube dashboard &

- name: Configure upstreams 
  shell: kubectl apply -f /vagrant/kubernetes/dashboard.yml && \
    kubectl apply -f /vagrant/kubernetes/grafana.yml
