apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-app
  namespace: dev
  labels:
    app: dev-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-app
        image: localhost:5000/myapp:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        - containerPort: 9991
        readinessProbe:
          httpGet:
            port: 3000
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 2
        livenessProbe:
          httpGet:
            port: 3000
            path: /liveness
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: ENVIRONMENT
          value: "dev"

---

kind: Service
apiVersion: v1
metadata:
  name: dev-app-upstream
  namespace: dev
  labels:
    k8s-app: dev-app
spec:
  selector:
    app: dev-app
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: main
    - port: 9991
      protocol: TCP
      targetPort: 9991
      name: metrics

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-app-upstream
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/app-root: /hello
    nginx.ingress.kubernetes.io/proxy-body-size: 4g
    nginx.ingress.kubernetes.io/server-snippet: |
      access_log /var/log/nginx/dev-app.access.log;
      error_log /var/log/nginx/dev-app.error.log;
      gzip on;
      gzip_disable "msie6";
      gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;
spec:
  rules:
  - host: dev.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: dev-app-upstream
          servicePort: 3000
